<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algorithmObjects" nsURI="ovgu.pave.algorithmObjects" nsPrefix="alg">
  <eClassifiers xsi:type="ecore:EClass" name="SearchStatistics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iterationsBeforeAcceptance"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfAcceptances" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfReschedulableRequests"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invalidDueCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invalidDueTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onTheFlyRescheduling" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wayPoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="removalIterations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Route" instanceClassName="ovgu.pave.model.solution.Route"/>
  <eClassifiers xsi:type="ecore:EClass" name="InsertionInformation">
    <eOperations name="setScoreForRegretHeuristic">
      <eParameters name="regretValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertionOptions" upperBound="-1"
        eType="#//InsertionOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="request" lowerBound="1"
        eType="#//Requests"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RouteElement" instanceClassName="ovgu.pave.model.solution.RouteElement"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ReuqestsHashMap" instanceClassName="java.util.HashMap&lt;ovgu.pave.model.input.Request, java.lang.Long>"/>
  <eClassifiers xsi:type="ecore:EClass" name="InsertionOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="costs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstActivityIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondActivityIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="route" eType="#//Route"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Requests" instanceClassName="ovgu.pave.model.input.Request"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemovalOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="route" eType="#//Route"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstActivityRouteElement"
        eType="#//RouteElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondActivityRouteElement"
        eType="#//RouteElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shawDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shawServiceBegin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemovalInformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRemovalsPerRequest"
        eType="#//ReuqestsHashMap"/>
  </eClassifiers>
</ecore:EPackage>
